name = "JavisNB"
uuid = "92afb270-2599-44f6-96a1-44c6efb1daf1"
authors = ["Jacob Zelko <jacobszelko@gmail.com>", "Giovanni Puccetti <giovanni.puccetti@sns.it>"]
version = "0.7.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
julia = "1.5"
